# .github/workflows/release.yml

name: Build and Publish to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out the repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: run-vcpkg
        uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgDirectory: ${{ env.VCPKG_ROOT }}
          runVcpkgInstall: true

      - name: Set up QEMU (for Linux ARM64 builds)
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3

      - name: 🔍 Debug Environment Variables
        run: |
          echo "VCPKG_ROOT is: ${{ env.VCPKG_ROOT }}"
          echo "CIBW_CMAKE_ARGS should be: -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake"

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        env:
          CIBW_BUILD: "cp310-* cp311-* cp312-*"
          CIBW_CMAKE_ARGS: -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake
          CIBW_ARCHS_LINUX: auto aarch64
          CIBW_ARCHS_WINDOWS: auto ARM64

      - name: Store wheels as artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  publish_wheels:
    name: Publish wheels to PyPI
    needs: [build_wheels]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: python-wheels-*
          merge-multiple: true

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}