# .github/workflows/release.yml

name: Build and Publish to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg

jobs:
  build_and_publish:
    name: Build and publish Python distributions to PyPI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install C++ dependencies with vcpkg
        uses: run-vcpkg/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ env.VCPKG_ROOT }}
          runInstall: true

      # QEMU is only needed for Linux ARM64 builds
      - name: Set up QEMU (for Linux ARM64 builds)
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        env:
          CIBW_CMAKE_ARGS: -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake
          CIBW_ARCHS_LINUX: auto aarch64
          CIBW_SKIP: "*-win32* *-manylinux_i686*"


      - name: Publish package to PyPI
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}