name: Build and Publish macOS Wheels

on:
  release:
    types: [created]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels for macOS (arm64)
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Required for cibuildwheel to get a clean version number.
          fetch-depth: 0

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.2
        env:
          MACOSX_DEPLOYMENT_TARGET: "15.0"
          CIBW_BUILD: "cp310-* cp311-* cp312-* cp313-*"
          CIBW_ARCHS_MACOS: arm64
          CIBW_BEFORE_BUILD: "brew install sdl2 opencv pybind11"

      - name: Store wheels as artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-wheels
          path: ./wheelhouse/*.whl

  publish_to_pypi:
    name: Publish wheels to PyPI
    needs: build_wheels
    runs-on: ubuntu-latest
    # if: github.event_name == 'release' && github.event.action == 'created'

    steps:
      - name: Download wheels from artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-wheels
          path: dist

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

