name: Build and Publish macOS Wheels

on:
  release:
    types: [created]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

# jobs:
#   build_wheels:
#     name: Build wheels for macOS (arm64)
#     runs-on: macos-latest
#     strategy:
#           fail-fast: false
#           matrix:
#             include:
#               - macos_version: "12"
#                 runner: "macos-12"
#               - macos_version: "13"
#                 runner: "macos-13"
#               - macos_version: "14"
#                 runner: "macos-14"
#               - macos_version: "15"
#                 runner: "macos-15"
#               - macos_version: "26"
#                 runner: "macos-26"

jobs:
  build_wheels:
    name: Build wheels for macOS ${{ matrix.macos_version }} (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # macOS 12
          - macos_version: "12"
            runner: "macos-12"
            arch: "arm64"
          - macos_version: "12"
            runner: "macos-12"
            arch: "x86_64"
            
          # macOS 13
          - macos_version: "13"
            runner: "macos-13"
            arch: "arm64"
          - macos_version: "13"
            runner: "macos-13"
            arch: "x86_64"

          # macOS 14
          - macos_version: "14"
            runner: "macos-14"
            arch: "arm64"
          - macos_version: "14"
            runner: "macos-14"
            arch: "x86_64"

          # macOS 15
          - macos_version: "15"
            runner: "macos-15"
            arch: "arm64"
          - macos_version: "15"
            runner: "macos-15"
            arch: "x86_64"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Required for cibuildwheel to get a clean version number.
          fetch-depth: 0

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.2
        env:
          MACOSX_DEPLOYMENT_TARGET: "${{ matrix.macos_version }}.0"
          # MACOSX_DEPLOYMENT_TARGET: "15.0"
          CIBW_BUILD: "cp310-* cp311-* cp312-* cp313-*"
          # CIBW_ARCHS_MACOS: arm64
          CIBW_ARCHS_MACOS: "${{ matrix.arch }}"
          # CIBW_BEFORE_BUILD: "brew install sdl2 opencv pybind11"
          CIBW_BEFORE_BUILD: >
                      brew install --build-from-source sdl2 opencv pybind11

      - name: Store wheels as artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-wheels-${{ matrix.runner }}-${{ matrix.arch }}
          # name: macos-wheels-${{ matrix.runner }}
          # name: macos-wheels
          path: ./wheelhouse/*.whl

  publish_to_pypi:
    name: Publish wheels to PyPI
    needs: build_wheels
    runs-on: ubuntu-latest
    # if: github.event_name == 'release' && github.event.action == 'created'

    steps:
      - name: Download wheels from artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-wheels-*
          # name: macos-wheels
          path: dist
          merge-multiple: true # New

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

