# A simple workflow to build a Python sdist and wheel on Windows.
# This file should be placed in the .github/workflows/ directory of your repository.

name: Build Python Package

on:
  # Triggers the workflow on push or pull request events for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:
      # Step 1: Check out your repository code so the workflow can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up a Python environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'arm64'

      - uses: tecolicom/actions-install-and-cache@v1
        with:
          run:  brew install sdl2 opencv pybind11
          path: /usr/local
          verbose: true

      # Step 6: Install the 'build' package itself, which is required to run the build command
      - name: Install build tool
        run: python -m pip install --upgrade build

      # Step 7: Run the build command as requested
      - name: Build sdist and wheel
        run: python -m build -v -sw

